erDiagram
  
  "iam.actions" {
      INTEGER action_id PK
      INTEGER service_id FK
      VARCHAR name 
      VARCHAR reference_url 
      BOOLEAN permission_only_flag 
      VARCHAR access_level 
    }
    "iam.services" ||--o{ "iam.actions" : has
    "iam.actions_condition_keys" {
      BIGINT action_condition_key_id PK
      BIGINT action_resource_type_id 
      INTEGER action_id FK
      INTEGER condition_key_id FK
    }
    "iam.actions" ||--o{ "iam.actions_condition_keys" : has
    "iam.condition_keys" ||--o{ "iam.actions_condition_keys" : has
    "iam.actions_dependant_actions" {
      INTEGER action_dependent_action_id PK
      BIGINT action_resource_type_id FK
      INTEGER action_id FK
      INTEGER dependent_action_id 
    }
    "iam.actions" ||--o{ "iam.actions_dependant_actions" : has
    "iam.actions_resource_types" ||--o{ "iam.actions_dependant_actions" : has
    "iam.actions_resource_types" {
      BIGINT action_resource_type_id PK
      INTEGER action_id FK
      INTEGER resource_type_id 
      BOOLEAN required_flag 
    }
    "iam.actions" ||--o{ "iam.actions_resource_types" : has
    "iam.condition_keys" {
      INTEGER condition_key_id PK
      VARCHAR name 
      VARCHAR reference_url 
      VARCHAR description 
      VARCHAR type 
    }

    "iam.resource_types" {
      INTEGER resource_type_id PK
      INTEGER service_id FK
      VARCHAR name 
      VARCHAR reference_url 
      VARCHAR arn_pattern 
    }
    "iam.services" ||--o{ "iam.resource_types" : has
    "iam.resource_types_condition_keys" {
      INTEGER resource_type_condition_key_id PK
      INTEGER resource_type_id FK
      INTEGER condition_key_id FK
    }
    "iam.resource_types" ||--o{ "iam.resource_types_condition_keys" : has
    "iam.condition_keys" ||--o{ "iam.resource_types_condition_keys" : has
    "iam.services" {
      INTEGER service_id PK
      VARCHAR name 
      VARCHAR prefix 
      VARCHAR reference_url 
    }
